version: '3'

services:
  app:
    build:
      ./app
    environment:
      - PORT=5001
    ports:
    - 5001:5001
  website:
    image: danjellz/http-server
    ports:
      - 8000:8080
    volumes:
      - ./website:/public